// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// index
void index(Rcpp::CharacterVector& dbpath, Rcpp::DataFrame& dataFrame, Rcpp::NumericVector& idColumn, Rcpp::List& indexFields, Rcpp::CharacterVector& stemmer);
RcppExport SEXP RXapian_index(SEXP dbpathSEXP, SEXP dataFrameSEXP, SEXP idColumnSEXP, SEXP indexFieldsSEXP, SEXP stemmerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type dbpath(dbpathSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type dataFrame(dataFrameSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type idColumn(idColumnSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type indexFields(indexFieldsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector& >::type stemmer(stemmerSEXP);
    index(dbpath, dataFrame, idColumn, indexFields, stemmer);
    return R_NilValue;
END_RCPP
}
