# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' indexing wrapper.
#'
#' @param dbpath	path to a Xapian database
#' @param dataFrame	data frame to be indexed
#' @param idColumn	index of a column in the data frame whose row value will be used as a unique identifier to each document(row).
#' @param indexFields	list of 'list of fields' that will be indexed using a Xapian::TermGenerator
#' @param stemmer 	the stemmer that should be applied to the Xapian::TermGenerator
#'
#' @export
#'
#'
index <- function(dbpath, dataFrame, idColumn, indexFields, stemmer) {
    invisible(.Call('RXapian_index', PACKAGE = 'RXapian', dbpath, dataFrame, idColumn, indexFields, stemmer))
}

